Create dynamic groups in AzureAD and the VB365 jobs accordingly
VeeamHub/powershell pull request #183
Opened 2023-06-13 18:56 UTC by d-works42

# Pull Request Template

By contributing, you agree that your contributions will be licensed under the projects original open source license.

## Description

This is an extension of the script VBO-CreateDynamicGroups to create the VB365 jobs accordingly. Also, the dynamic groups membership rules have been extended.

Fixes # (issue)

### Type of change

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

### How Has This Been Tested?

Testet in personal lab and at one customer.

### Checklist (check all applicable):

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in _hard to understand_ areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes

2023-06-27 16:01 UTC, carceneaux commented
Thanks for your contribution, @d-works42!

After skimming the PR, can you please update the README file letting others know which Veeam Backup for Microsoft 365 versions the script was tested against and/or supports.

Here's a sample README you can use as a reference:

https://github.com/VeeamHub/powershell/blob/master/VB365-ExportMailboxToPST/README.md

2023-07-05 16:47 UTC, carceneaux requested changes
Please correct changes and then this PR will be good to merge.

2023-07-05 16:47 UTC, carceneaux commented on VB365-UserJobsDynamicGroups/README.md
Please update the README file letting others know which Veeam Backup for Microsoft 365 versions the script was tested against and/or supports.

Here's a sample README you can use as a reference:

https://github.com/VeeamHub/powershell/blob/master/VB365-ExportMailboxToPST/README.md

2024-02-23 09:35 UTC, d-works42 commented on VB365-UserJobsDynamicGroups/README.md
I somehow came over this comment, edited now.

2025-03-05 08:46 UTC, closed without merging